version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
environment:
  APPVEYOR_RDP_PASSWORD: Julia2007Leon2009$
install:
- cmd: >-
    if exist "c:\projects\Dolphin\" rmdir /s /q "C:\projects\Dolphin\"

    git clone https://github.com/dolphinsmalltalk/Dolphin.git C:\projects\Dolphin

    cd C:\projects\Dolphin & git submodule update --init --recursive & git lfs pull



    FetchVm



    BootDPRO
build_script:
- cmd: echo Only Test
test_script:
- cmd: >-
    SET PATH=C:\projects\Dolphin;%PATH%



    cd %APPVEYOR_BUILD_FOLDER% & RunTests