version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
init:
- cmd: >-
    if not exist "C:\projects\Dolphin\" git clone https://github.com/dolphinsmalltalk/Dolphin.git C:\projects\Dolphin
    cd C:\projects\Dolphin
    git fetch all
    git reset --hard origin/master
    git submodule update --init --recursive
    git lfs pull
    FetchVm
    BootDPRO
clone_folder: c:\projects\Dolphin\DolphinHttpServer
build_script:
- cmd: >-
    echo Nothing to build only test
test_script:
- cmd: >-
    SET PATH=C:\projects\Dolphin;%PATH%
    
    
    RunTests
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\RegressionTests.xml))
notifications:
- provider: Email
  to:
  - fxgallego@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
