version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
environment:
  APPVEYOR_RDP_PASSWORD: Julia2007Leon2009$
install:
- ps: >-
    Remove-Item "C:\projects\Dolphin" -Force -Recurse
    
    $r = Invoke-RestMethod "https://api.github.com/repos/dolphinsmalltalk/Dolphin/releases/latest"
    
    git clone --single-branch --branch $r.tag_name https://github.com/dolphinsmalltalk/Dolphin.git C:\projects\Dolphin
    
    cd "C:\projects\Dolphin"
    
    git submodule update --init --recursive
    
    git lfs pull
    
    .\FetchVM.cmd
    
    .\BootDPRO.cmd
build_script:
- cmd: echo Only Test
test_script:
- cmd: >-
    SET PATH=C:\projects\Dolphin;%PATH%



    cd %APPVEYOR_BUILD_FOLDER% & RunTests
